name: Build
on: [push, pull_request]
jobs:
    test:
        name: Test
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@master
            - name: Checkout
              if: github.ref == 'refs/heads/main'
              run: git checkout "${GITHUB_REF:11}"
            - name: Composer Install
              run: composer install
            - name: PHPCS
              run: ./vendor/bin/phpcs src tests
            - name: Run Tests
              run: ./vendor/bin/pest

    release:
        name: Release
        if: github.ref == 'refs/heads/main'
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master
            - name: Setup Node.js
              uses: actions/setup-node@latest
              with:
                  node-version: 20
            - name: Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: npx semantic-release@latest
