name: Build
on: [push, pull_request]
jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Checkout
              if: github.ref == 'refs/heads/main'
              run: git checkout "${GITHUB_REF:11}"
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: 8.3
                extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick
                coverage: none
            - name: Composer Install
              run: composer install
            - name: PHP Linting
              run: composer lint
            - name: Run Tests
              run: ./vendor/bin/pest

    release:
        name: Release
        if: false && github.ref == 'refs/heads/main'
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master
            - name: Setup Node.js
              uses: actions/setup-node@4
              with:
                  node-version: 20
            - name: Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: npx semantic-release@latest
